name: cjvm_app
description: A new Flutter project.

publish_to: "none"

version: 1.5.0+62

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  add_2_calendar: ^3.0.1
  cached_network_image: ^3.3.0
  flutter_html: ^3.0.0-beta.2
  flutter_launcher_icons: ^0.13.1
  flutter_platform_widgets: ^6.0.2
  html: ^0.15.4
  http: ^1.1.2
  intl: ^0.18.0
  maps_launcher: ^2.2.0
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  table_calendar: ^3.0.9
  url_launcher: ^6.2.2
  #firebase_messaging: ^14.6.7

  cupertino_icons: ^1.0.5

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
