// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUkl8cn8-2CDpJM083grSk8uws_-pXYIY',
    appId: '1:168778905526:web:451f347d1e54a5d8117317',
    messagingSenderId: '168778905526',
    projectId: 'cvjm-274115',
    authDomain: 'cvjm-274115.firebaseapp.com',
    databaseURL: 'https://cvjm-274115.firebaseio.com',
    storageBucket: 'cvjm-274115.appspot.com',
    measurementId: 'G-5JMN1G5ZKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMTgLCcYU9W0aECm1fue4HqPUp5HPZWic',
    appId: '1:168778905526:android:d86f428dcbea90d2117317',
    messagingSenderId: '168778905526',
    projectId: 'cvjm-274115',
    databaseURL: 'https://cvjm-274115.firebaseio.com',
    storageBucket: 'cvjm-274115.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-NtbZ0BNICsGaMr617uHrQ-ude3ZkmXA',
    appId: '1:168778905526:ios:52122d5e291993f3117317',
    messagingSenderId: '168778905526',
    projectId: 'cvjm-274115',
    databaseURL: 'https://cvjm-274115.firebaseio.com',
    storageBucket: 'cvjm-274115.appspot.com',
    iosClientId: '168778905526-evvddnakcq5let2nj53j5fbh204te81j.apps.googleusercontent.com',
    iosBundleId: 'de.cvjm-walheim.cvjm-app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-NtbZ0BNICsGaMr617uHrQ-ude3ZkmXA',
    appId: '1:168778905526:ios:9a0d4cb1ea3a134b117317',
    messagingSenderId: '168778905526',
    projectId: 'cvjm-274115',
    databaseURL: 'https://cvjm-274115.firebaseio.com',
    storageBucket: 'cvjm-274115.appspot.com',
    iosBundleId: 'com.example.cjvmApp',
  );
}
